### ISSUE TITLE
.bbl file not created

### ISSUE THREAD

**Issue by thearquitec** [LaTeXing/LaTeXing#132] opened 2015-04-14 20:00 UTC
I'm building a tex document which uses a bib file. Once I compile it, the following warnings are generated.
No file name.bbl. 
There were undefined citations.

I have tried running the same code in TexShop and the pdf is compiled correctly, including the references I used. While running TexShop the file name.bbl and name.blg are created, something that did not happen with Sublime Text.  After doing some research, I believe the problem might be related with latexmk but I'm not sure how to proceed. Any thoughts on this? 

Thanks

**Comment by smithdanielle** [comment] 2015-04-15 10:54
This is a possible duplicate of issue [#128](https://github.com/LaTeXing/LaTeXing/issues/128).

**Comment by csch0** [comment] 2015-04-15 17:14
Thanks @smithdanielle. @thearquitec please could you please do the same like explained [here](https://github.com/LaTeXing/LaTeXing/issues/128#issuecomment-91153702)

**Comment by thearquitec** [comment] 2015-04-16 01:49
Thanks @smithdanielle and  @csch0, i tried what is describe in issue #128 and it worked. My tex file is compiled correctly, including references and the .bbl file is created.  The implications of that is that every time I want to compile my file I need to hit command +l and after command + b, to build it with LaTex.

After running the check system for LaTexing, I notice the sublime executable is not within the searched paths. Therefore I linked the executable to the path directory using.    

sudo ln -s /Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl /usr/local/bin/sublime

Now i just need to compile the tex file in the usual way (command + b) and the bbl file is created and all the references are cited properly.

Thanks for your help, this solved my issue.

**Closed** 2015-04-20 09:28 UTC
